//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Capital
    {
        public int Id { get; set; }
        public decimal Cash { get; set; }
        public decimal DebitCardFirst { get; set; }
        public decimal DebitCardSecond { get; set; }
        public decimal DebitCardThird { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
