// <auto-generated />
using System;
using HouseholdFinances.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HouseholdFinances.Data.Migrations
{
    [DbContext(typeof(HouseholdFinancesContext))]
    [Migration("20190323172434_CreateTableExpenses")]
    partial class CreateTableExpenses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HouseholdFinances.Data.Models.Capital.Capital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cash");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<decimal>("DebitCardFirst");

                    b.Property<decimal>("DebitCardSecond");

                    b.Property<decimal>("DebitCardThird");

                    b.Property<decimal>("Total");

                    b.HasKey("Id");

                    b.ToTable("Capitals");
                });

            modelBuilder.Entity("HouseholdFinances.Data.Models.Expense.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Bills");

                    b.Property<DateTime>("Date");

                    b.Property<decimal>("Food");

                    b.Property<decimal>("Others");

                    b.Property<decimal>("PinMoney");

                    b.Property<decimal>("Transport");

                    b.HasKey("Id");

                    b.ToTable("Expenses");
                });
#pragma warning restore 612, 618
        }
    }
}
