// <auto-generated />
using System;
using HouseholdFinances.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HouseholdFinances.Data.Migrations
{
    [DbContext(typeof(HouseholdFinancesContext))]
    [Migration("20190219170517_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FamilyIncomeExpences.Data.Models.Capital.Capital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Cash");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<decimal>("DebitCardFirst");

                    b.Property<decimal>("DebitCardSecond");

                    b.Property<decimal>("DebitCardThird");

                    b.HasKey("Id");

                    b.ToTable("Capitals");
                });
#pragma warning restore 612, 618
        }
    }
}
